export const MAIN_ROUTE = '/hakaton'
export const USERS_ROUTE = '/hakaton/users'
export const SINGLE_USER_ROUTE = '/hakaton/users/:id'
export const ERROR_ROUTE = '/hakaton/error'
export const FAVORITE_ROUTE = '/hakaton/favorite'
export const COMMENT_ROUTE = '/hakaton/comments'
