export const MAIN_ROUTE = '/'
export const USERS_ROUTE = '/users'
export const SINGLE_USER_ROUTE = '/users/:id'
export const ERROR_ROUTE = '/error'
export const FAVORITE_ROUTE = '/favorite'
export const COMMENT_ROUTE = '/comments'
